apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drone-rid

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-statefulset.yaml
  - emqx-configmap.yaml
  - emqx-statefulset.yaml
  - emqx-service.yaml
  - mqtt-consumer-deployment.yaml
  - server-deployment.yaml
  - server-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: drone-rid

images:
  - name: drone-rid-center
    newTag: latest
